site_name: eTraining (ADMIN) Manual
theme:
  name: material
  
  
  #logo: img/logo.png
  
  features:
    - content.code.annotate
  #   - navigation.tabs
  #   - navigation.tabs.sticky
  font:
    text: Roboto
  palette:  
    # scheme: slate
    primary: indigo  
    accent: indigo
extra:
  version:
    provider: mike
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
  - css/style.css
nav:  
  - Pengenalan: index.md
  - Dokumen Rujukan: manual.md  
  - Pelaksanaan Kursus: pelaksanaan_kursus.md
  - Kod Kursus: linkup_code.md
  - Bajet Kursus: bajet_kursus.md
  - Status Kursus: status_kursus.md
  - Upload Banner Kursus: banner.md
  - Penjanaan Dokumen ISO: dokumen_iso.md
  - Surat Panggilan Kursus: slip_panggilan.md
  
